### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by JoshDrummReid** [Tautulli/Tautulli#1407] opened 2021-04-11 17:22 UTC
Hi Guys,

After updating to V2.7.0 I keep getting 500 Internal Server Error under Watch Statistics,

Attached are my logs,

Thanks you,
[tautulli.log](https://github.com/Tautulli/Tautulli/files/6292344/tautulli.log)

**Comment by JonnyWong16** [comment] 2021-04-11 20:12
Python 2 is no longer supported.
![](https://i.imgur.com/QVad7La.png)
https://github.com/Tautulli/Tautulli/wiki/Upgrading-to-Python-3-%28Tautulli-v2.5%29
```
2021-04-11 12:56:44 - INFO    :: MainThread : Python 2.7.16 (default, May  6 2019, 19:28:45) [GCC 8.3.0]
```

And you need to fix your database (using the "Long Way" from the FAQ).
https://github.com/Tautulli/Tautulli/wiki/Frequently-Asked-Questions#general-q18
```
2021-04-11 12:56:45 - ERROR   :: MainThread : Can't connect to the database: UNIQUE constraint failed: cloudinary_lookup.img_hash
```

**Comment by JonnyWong16** [comment] 2021-04-11 20:17
This is not a bug, so I am closing this issue. Please use the [Discord Server](https://tautulli.com/discord) for further support.

**Closed as completed by JonnyWong16** 2021-04-11 20:17 UTC
Labels: invalid:template-incomplete
