### ISSUE TITLE
Duplicate Libraries - They are all listed twice, but with not the same content count.

### ISSUE THREAD

**Issue by pducharme** [Tautulli/Tautulli#543] opened 2016-02-14 00:29 UTC
Hi, I'm running latest PlexPy in a Docker on my Unraid Server.  It is working fine, but I see that since the "Librairies" was added, all my librairies are listed twice.

<img width="938" alt="screen1" src="https://cloud.githubusercontent.com/assets/1879339/13030916/0e63c3f6-d288-11e5-8e5e-3535d04a0706.png">

**Comment by JonnyWong16** [comment] 2016-02-14 00:33
Please search before opening a new issue.
Duplicate of #491. Possible solutions in that thread. https://github.com/drzoidberg33/plexpy/issues/491#issuecomment-179020466

**Closed as completed by JonnyWong16** 2016-02-14 00:33 UTC
Labels: invalid:duplicate
