### ISSUE TITLE
Notifications recently added doesnt work

### ISSUE THREAD

**Issue by Mascalerino** [Tautulli/Tautulli#1431] opened 2021-05-06 11:56 UTC
**Describe the Bug**
Notifications are not sent to telegram when something is added to plex. In the logs I see that all notifications are created but some reach telegram but most do not.

**Steps to Reproduce**
1. Add a something to plex

**Expected Behavior**
If something is added to plex, Tautulli would have to send a notification to telegram.

**Tautulli and System Info (see Tautulli settings page)**
- Version: 2.7.2
- Git Branch: master
- Git Commit Hash: 39ad3f9047fb3f8ed7b18b1584b079a70280d37b
- Platform and Version: Linux 4.15.0-142-generic - Ubuntu 16.04 xenial
- Python Version: 3.6.2

**Link to logs (required)**
Include a link to your **FULL** logs (not just a few lines) on [Gist](http://gist.github.com).

[tautulli.log](https://github.com/Tautulli/Tautulli/files/6434174/tautulli.log)

**Comment by JonnyWong16** [comment] 2021-05-06 16:29
> Include a link to your FULL logs (not just a few lines) on Gist.

Logs must be uploaded to gist. We will not download attachments.

**Comment by Mascalerino** [comment] 2021-05-07 07:01
> > Include a link to your FULL logs (not just a few lines) on Gist.
> 
> Logs must be uploaded to gist. We will not download attachments.

https://gist.github.com/Mascalerino/69f11d09d55d2b9e7a62935791990ba3

**Comment by JonnyWong16** [comment] 2021-05-07 17:33
Your recently added delay is way too short. Your Plex server has not had enough time to finish adding the item before Tautulli tries to get the metadata.

![image](https://user-images.githubusercontent.com/9099342/117487026-59c71b80-af1f-11eb-8ca2-8a04429ce0bc.png)

Closing this issue because it is not a bug report. Please use the [Discord server](https://tautulli.com/discord) if you continue to have issues regarding this.

**Closed as completed by JonnyWong16** 2021-05-07 17:33 UTC
Labels: invalid:support
