### ISSUE TITLE
Group “Watched” notifications by day or week

### ISSUE THREAD

**Issue by LwsBtlr** [Tautulli/Tautulli#1433] opened 2021-05-08 10:24 UTC
**Describe the solution you'd like**
While some notifications are important to get quickly, the watched notifications I do not need to get a separate email for every episode or movie that anyone watches, but a daily or even weekly email showing everything would be useful.

If it is possible to do this via the buffer and delay setting those options are not exactly clear on what they do and what they delay.

**Comment by samwiseg0** [comment] 2021-05-08 14:45
I think this is a duplicate of https://github.com/Tautulli/Tautulli/issues/1428. A newsletter type that contains statistics seems like a more fitting solution to what you want?

**Comment by JonnyWong16** [comment] 2021-05-08 16:05
All playback related notifications are based on event triggers so it does not make sense to group them like that. It you want that type of functionality then use a script notification to save the individual events and send yourself a notification later. This is not something that I will add to Tautulli.

**Closed as completed** 2021-05-08 16:06 UTC
Labels: type:enhancement, wont-fix
