### ISSUE TITLE
[Feature request] Skinning support

### ISSUE THREAD

**Issue by marciobooi** [Tautulli/Tautulli#246] opened 2015-10-13 20:37 UTC
hi great server monitor for plex i have 2 requests to make if its possible

1- can you make an option in settings menu to make all the web site white instead the black like a skin option? if fits i give the exemple of the app store or github .

2- graphs are great but it miss the hardware of the machine status, like processor("for transcode process"), memory, disk, velocity of net, and etc, etc

thanks a lot for the help and keep the good work if need help im one more to help

**Comment by Arcanemagus** [comment] 2015-10-13 20:44
Point 2 is a duplicate of https://github.com/drzoidberg33/plexpy/issues/175.

**Comment by drzoidberg33** [comment] 2015-10-14 10:22
It's currently quite easy for developers to create different skins for PlexPy, there isn't however a way to switch between these.

Everything in the `data/interfaces` folder is front-end stuff.

**Closed as completed** 2020-10-31 05:19 UTC
Labels: type:enhancement
