### ISSUE TITLE
Feature Request: Whatsapp as new notifications agent

### ISSUE THREAD

**Issue by Pakorro** [Tautulli/Tautulli#694] opened 2016-05-08 22:12 UTC
Hi, it will be possible to add WhatsApp for IOS / Android as new notifications agent?. A created users group receiving a reporting from Plexpy weekly...

Excuse me if this request or new feature is already posted...

Regards.

**Comment by Arcanemagus** [comment] 2016-05-08 22:13
Duplicate of https://github.com/drzoidberg33/plexpy/issues/624.

**Comment by drzoidberg33** [comment] 2016-05-08 22:59
https://github.com/drzoidberg33/plexpy#feature-requests

**Closed as completed by drzoidberg33** 2016-05-08 22:59 UTC
