### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mwhaley99** [Tautulli/Tautulli#655] opened 2016-04-08 00:05 UTC
I am getting this....

400 Bad Request

Illegal cookie name dm_enable

Traceback (most recent call last):
  File "/Applications/PlexPy/lib/cherrypy/_cprequest.py", line 635, in respond
    self.process_headers()
  File "/Applications/PlexPy/lib/cherrypy/_cprequest.py", line 737, in process_headers
    raise cherrypy.HTTPError(400, msg)
HTTPError: (400, 'Illegal cookie name dm_enable')
Powered by CherryPy 3.8.0

**Comment by JonnyWong16** [comment] 2016-04-08 01:24
Please read the guidelines before posting new issues:
https://github.com/drzoidberg33/plexpy#issues

Looks like duplicate of #523.

**Closed as completed** 2016-04-08 22:06 UTC
Labels: invalid:duplicate
