### ISSUE TITLE
[Feature Request] Filter by user(s) on Graphs tab

### ISSUE THREAD

**Issue by crushergad** [Tautulli/Tautulli#560] opened 2016-02-21 11:53 UTC
I think it would be interesting to see all the information that the Graphs tab provide for each user (or group of users), for example to see a specific user watching habits (Daily Play duration, Play duration by day of week and Play duration by hour of day).

I suppose this could be achieved by adding a "filter by user(s)" in the Graphs tab or by adding an individual Graphs page for each user.

What do you thin guys?

**Comment by JonnyWong16** [comment] 2016-02-21 16:45
Duplicate of #382

**Closed as completed** 2016-02-21 16:45 UTC
Labels: invalid:duplicate
