### ISSUE TITLE
Error when importing from plexWatch db

### ISSUE THREAD

**Issue by ooii** [Tautulli/Tautulli#24] opened 2015-07-23 13:38 UTC
Hi,

I have a 2 year database from plexWatch which I want to keep. As soon as the import starts, I have the following error:

```
23-jul-2015 15:34:30 - DEBUG :: Thread-18 : PlexPy Importer :: PlexWatch data import in progress...
23-jul-2015 15:34:30 - DEBUG :: Thread-18 : PlexPy Importer :: Disabling monitoring while import in progress.
23-jul-2015 15:34:30 - INFO :: Thread-18 : Requesting users list refresh...
23-jul-2015 15:34:32 - INFO :: Thread-18 : Users list refreshed.
23-jul-2015 15:34:32 - DEBUG :: Thread-18 : PlexPy Importer :: Item has bad rating_key: http://www.canalplus.fr/c-sport/c-football/pid6597-c-enquetes-de-foot.html?vid=992848
23-jul-2015 15:34:32 - ERROR :: Thread-18 : Uncaught exception: Traceback (most recent call last):
  File "/private/tmp/plexpy/plexpy/logger.py", line 210, in new_run
    old_run(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/private/tmp/plexpy/plexpy/plexwatch_import.py", line 363, in import_from_plexwatch
    if str(row[2]).isdigit():
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)

Traceback (most recent call last):
  File "/private/tmp/plexpy/plexpy/logger.py", line 210, in new_run
    old_run(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/private/tmp/plexpy/plexpy/plexwatch_import.py", line 363, in import_from_plexwatch
    if str(row[2]).isdigit():
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)
```

Note that I have a lot of french content which may cause this issue.

**Comment by drzoidberg33** [comment] 2015-07-23 13:45
Thanks for the report. I think I can see what the issue is and will push a fix in my next commit.

**Comment by ooii** [comment] 2015-07-23 16:56
Thanks. I'm expecting it.

**Comment by drzoidberg33** [comment] 2015-07-23 23:02
Please check if the latest commit https://github.com/drzoidberg33/plexpy/commit/b394ebc1a39fe2e6dc05cd10e0957ed8ac801cd6 helps with this issue.

**Comment by ooii** [comment] 2015-07-24 06:49
No, it does not.
Here is the output (seems the same):

```
24-jul-2015 08:48:58 - DEBUG :: Thread-13 : PlexPy Importer :: Item has bad rating_key: http://www.canalplus.fr/c-sport/c-football/pid6597-c-enquetes-de-foot.html?vid=992848
24-jul-2015 08:48:58 - ERROR :: Thread-13 : Uncaught exception: Traceback (most recent call last):
  File "/private/tmp/plexpy/plexpy/logger.py", line 210, in new_run
    old_run(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/private/tmp/plexpy/plexpy/plexwatch_import.py", line 363, in import_from_plexwatch
    if str(row[2]).isdigit():
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)

Traceback (most recent call last):
  File "/private/tmp/plexpy/plexpy/logger.py", line 210, in new_run
    old_run(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/private/tmp/plexpy/plexpy/plexwatch_import.py", line 363, in import_from_plexwatch
    if str(row[2]).isdigit():
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-52: ordinal not in range(128)
```

**Comment by drzoidberg33** [comment] 2015-07-24 07:58
Hmm, very difficult for me to figure out what's causing this then without having the database. Is it possible you could share the database with me via dropbox, etc?

If you don't have issues with it you can share to my email address timvdwest (at) gmail.com

This would be the fastest solution otherwise I have to do a bunch of trial and error.

**Comment by ooii** [comment] 2015-07-24 09:15
I understand. I can, of course, share it with you: https://www.dropbox.com/s/0ypqu0cyctox5wt/plexWatch.db?dl=0

## 

Farid.

**Comment by drzoidberg33** [comment] 2015-07-24 09:35
Thank you, I'll look at this later today and provide a fix.

**Comment by ooii** [comment] 2015-07-24 10:11
## Thanks. Can I delete the file from dropbox?

Farid.

**Comment by drzoidberg33** [comment] 2015-07-24 10:13
Yes thanks I have already added it to my Dropbox account.

**Comment by drzoidberg33** [comment] 2015-07-24 20:51
Thanks so much for sharing the file, I have fixed the problem and some other issues along the way.

Please update to https://github.com/drzoidberg33/plexpy/commit/5a9257074b52c82534ff317367d3da7de1a62f38, shut PlexPy down and delete any database files in your plexpy folder (plexpy.db, plexpy.db-wal, plexpy.db-shm) - this will delete any history logged in PlexPy already. Then restart again and try to import, or you can just do a clean install.

Let me know if you run into any more issues.

**Comment by ooii** [comment] 2015-07-25 06:41
Thanks, it's OK now.

**Comment by drzoidberg33** [comment] 2015-07-25 08:39
Confirmed fixed. Closing.

**Closed as completed by drzoidberg33** 2015-07-25 08:39 UTC
Labels: type:bug
