### ISSUE TITLE
Reboot NAS and configuration goes away.

### ISSUE THREAD

**Issue by Elrique64** [Tautulli/Tautulli#10] opened 2015-07-07 22:43 UTC
This is MikeG from the Plex Forums.  Every time I reboot my NAS, the config for PlexPy totally disappears.  Default ports, server addresses, log file locations all go away.  Today, after a reboot, the only way to get back into PlexPy was to delete the config file completely and have the script make a new one.  Even after doing that, the ports I had setup still didn't work.  I made a new port forward rule on the router, for the external port I want to use, pointing to 8181.  

I checked the file contents and creation dates for config.ini and they were the same as when I had last edited the file.  I think somehow, when the script runs, the first time after reboot, it thinks there is no config file and tries to make one, and somehow fails.

All-in-all, you are making a great app here.  I hope to see the work you are doing get due recognition!

**Comment by drzoidberg33** [comment] 2015-07-08 08:28
Hey.

Does this happen only after a reboot of the system or also when you shutdown/restart just the PlexPy app?

It may be caused by the app being shutdown improperly when the reboot occurs. Next time you reboot try and shutdown PlexPy first, then reboot. Then check if your settings are still there.

I'll add some more debug logging in the next commit to help figure out what's happening with the config file on startup.

**Comment by Elrique64** [comment] 2015-07-08 15:34
It happens only when the system reboots.  I haven't tried shutting the app down before rebooting, though.  I will give it a try next time I need to power down.

The file never disappears.  And none of the settings inside the file appear changed, either.  It's like it's running a first time run with default settings, and then it hangs.  I'm sure it's not permissions, because the script is running as root with root access to all files.

**Comment by drzoidberg33** [comment] 2015-07-24 11:49
Any update on this? Is this still happening?

I haven't seen any other reports of this so far.

**Comment by drzoidberg33** [comment] 2015-08-11 16:03
No feedback on this in almost 3 weeks so I'm assuming it's no longer happening. Closing issue.

**Closed as completed by drzoidberg33** 2015-08-11 16:03 UTC
